### PR TITLE
Handle crashes from form invalid forms, sub-forms, rules & properties files

### LINKED ISSUE #527: Handle crashes from form invalid forms, sub-forms, rules & properties files
- [ ] Add a global error handler insider the JSON Form activity (Than can rethrow the exception if it is not handled) **_(Moved)_**
- [x] Enable rollback to previous version via a user prompt
- [x] Inform the user that the rollback is going to happen -> If a previous version is available
- [ ] Add a method that receives thrown exceptions . One param should say if the error should be rethrown if not handled (This will work for silent exceptions on native-form that should work as is for current applications but revert to previous form on doc-config enabled apps)**_(Moved)_**
- [ ] There will be a activity/global error handler that handles uncaught exceptions i.e. RuntimeExceptions which cause crashing and ask the user if it can revert to the previous stable form for that app version. A different app version might mean that the data model is different and is therefore not compatible with the fallback form.**_(Moved)_**
- [ ] This global/activity error handler is limited to uncaught exceptions whereas many exceptions are handled inside native form **_(Moved)_**
- [x] Fatal errors & syntax errors are caught before opening the form - This can be handled to mean the new form is unstable
- [ ] ~Handle exceptions due to missing rules files & sub-form files - This exception will be passed over to the activity error handler~ We do not have a way to handle this since there will always be a default asset file. The developers of native-form should handle wrong references when the returned JSONObject is null or rules doesn't contain anything
- [x] Handle exceptions due to syntactic error in rules files & sub-form files & pass them over to the activity error handler
- [x] No fatal error would occur inside the JsonFormActivity due to form content

### PR DESCRIPTION
**Pull request by ekigamba**
Fixes #527

### CODE REVIEW

**Comment by keymane** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- opensrp-app/src/main/java/org/smartregister/view/activity/DynamicJsonFormActivity.java  3
- opensrp-app/src/main/java/org/smartregister/util/ViewUtil.java  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/OpenSRP/opensrp-client-core/pullRequest?prid=5565225&bid=18250044)

**Comment by keymane** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- opensrp-app/src/main/java/org/smartregister/util/ViewUtil.java  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/OpenSRP/opensrp-client-core/pullRequest?prid=5565225&bid=18250044)

**Comment by ekigamba** [comment]
Depends on #528

**Comment by keymane** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- opensrp-app/src/test/java/org/smartregister/view/dialog/FormRollbackDialogTest.java  1
- opensrp-app/src/main/java/org/smartregister/view/dialog/FormRollbackDialog.java  5
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/OpenSRP/opensrp-client-core/pullRequest?prid=5565225&bid=18250044)

**Comment by keymane** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- opensrp-app/src/main/java/org/smartregister/view/dialog/FormRollbackDialog.java  5
- opensrp-app/src/test/java/org/smartregister/view/dialog/FormRollbackDialogTest.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/OpenSRP/opensrp-client-core/pullRequest?prid=5565225&bid=18250044)

**Comment by keymane** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- opensrp-app/src/main/java/org/smartregister/view/dialog/FormRollbackDialog.java  5
- opensrp-app/src/test/java/org/smartregister/view/dialog/FormRollbackDialogTest.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/OpenSRP/opensrp-client-core/pullRequest?prid=5565225&bid=18250044)

**Comment by keymane** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- opensrp-app/src/main/java/org/smartregister/view/activity/FormConfigurationJsonFormActivity.java  3
- opensrp-app/src/test/java/org/smartregister/view/activity/FormConfigurationJsonFormActivityTest.java  1
- opensrp-app/src/main/java/org/smartregister/view/dialog/FormRollbackDialog.java  5
- opensrp-app/src/test/java/org/smartregister/view/dialog/FormRollbackDialogTest.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/OpenSRP/opensrp-client-core/pullRequest?prid=5565225&bid=18250044)

File: opensrp-app/src/main/java/org/smartregister/util/FormUtils.java [hunk 1]
```diff
@@ -1130,11 +1135,64 @@ private void createNewClientDocument(org.smartregister.cloudant.models.Client cl
...
 
+        if (onFormFetchedCallback != null) {
+            onFormFetchedCallback.onFormFetched(jsonObject);
+            return null;
+        }  else {
+            return jsonObject;
+        }
+    }
+
+    private ClientForm getClientFormFromRepository(String formIdentity) {
```
Comment (dubdabasoduba) [inline opensrp-app/src/main/java/org/smartregister/util/FormUtils.java:1192]: Does this account for MLS v2.0 where even if the locale changes we still the same form?

File: opensrp-app/src/main/java/org/smartregister/util/FormUtils.java [hunk 2]
```diff
@@ -1146,25 +1204,60 @@ public JSONObject getFormJsonFromRepositoryOrAssets(String formIdentity) {
...
-                JSONObject formJson = new JSONObject(clientForm.getJson());
-                injectFormStatus(formJson, clientForm);
+    public void handleJsonFormOrRulesError(boolean isRulesFile, @NonNull String formIdentity, @NonNull OnFormFetchedCallback<String> onFormFetchedCallback) {
+        ClientForm clientForm = getClientFormFromRepository(formIdentity);
+        ClientFormRepository clientFormRepository = CoreLibrary.getInstance().context().getClientFormRepository();
+        List<ClientForm> clientForms = clientFormRepository.getClientFormByIdentifier(clientForm.getIdentifier());
+
+        if (clientForms.size() > 0) {
+            // Show dialog asking user if they want to rollback to the previous available version X
+            // if YES, then provide that form instead
```
Comment (dubdabasoduba) [inline opensrp-app/src/main/java/org/smartregister/util/FormUtils.java:1221]: Are we checking for the APK compatibility when suggesting the form rollback version.

File: opensrp-app/src/main/java/org/smartregister/view/activity/FormConfigurationJsonFormActivity.java [hunk 3]
```diff
@@ -70,7 +74,7 @@ public void run() {
                 });
     }
 
-    @NonNull
+    @Nullable
```
Comment (dubdabasoduba) [inline opensrp-app/src/main/java/org/smartregister/view/activity/FormConfigurationJsonFormActivity.java:77]: Hope you are checking for nulls in the places where these methods are used

File: opensrp-app/src/main/java/org/smartregister/util/FormUtils.java (hunk 1 above)
Comment (ekigamba) [reply opensrp-app/src/main/java/org/smartregister/util/FormUtils.java:1192]: Nope, I probably didn't get this question. Can you table this for the meeting? 

I have not put a lot of effort on MLS v2 support due to the inability to clearly test but as long as the property files are considered as forms, the idea is that it would only require enabling the DB as a source of property files also(instead of just the assets)

File: opensrp-app/src/main/java/org/smartregister/util/FormUtils.java (hunk 2 above)
Comment (ekigamba) [reply opensrp-app/src/main/java/org/smartregister/util/FormUtils.java:1221]: Nope, we are not. As discussed, we provide the user with all the available forms. 

1. The logic for providing the option ended up being too complicated & would take a lot of effort
2. Our assumption that app version means a change in app-model is not accurate. The idea is that the model might remain the same across multiple app versions and thus we cannot accurately determine or suggest to the user the model-compatible forms

File: opensrp-app/src/main/java/org/smartregister/view/activity/FormConfigurationJsonFormActivity.java (hunk 3 above)
Comment (ekigamba) [reply opensrp-app/src/main/java/org/smartregister/view/activity/FormConfigurationJsonFormActivity.java:77]: Yea

File: opensrp-app/src/main/java/org/smartregister/util/FormUtils.java (hunk 1 above)
Comment (dubdabasoduba) [reply opensrp-app/src/main/java/org/smartregister/util/FormUtils.java:1192]: Added, thanks.

File: opensrp-app/src/main/java/org/smartregister/util/FormUtils.java (hunk 2 above)
Comment (dubdabasoduba) [reply opensrp-app/src/main/java/org/smartregister/util/FormUtils.java:1221]: What happens if I update the registration form & update the registration form logic and add/remove new questions or hidden fields e.g `contact_no` which are key to the rest of the app logic? If we roll back to a version that doesn't have this field then use the new APK then the logic will be messed up.

Comment (Kigamba) [reply opensrp-app/src/main/java/org/smartregister/util/FormUtils.java:1221]: We do not automatically rollback, we give the user the option, We cannot also tell critical and non-critical changes. That would require extra work to determine. What do you think?Do you have a suggestion that accurately determines compatible rollback form(s)?

**Comment by keymane** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- opensrp-app/src/test/java/org/smartregister/view/activity/FormConfigurationJsonFormActivityTest.java  1
- opensrp-app/src/main/java/org/smartregister/view/activity/FormConfigurationJsonFormActivity.java  3
- opensrp-app/src/main/java/org/smartregister/view/dialog/FormRollbackDialogUtil.java  5
- opensrp-app/src/test/java/org/smartregister/view/dialog/FormRollbackDialogUtilTest.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/OpenSRP/opensrp-client-core/pullRequest?prid=5565225&bid=18250044)

**Comment by keymane** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- opensrp-app/src/test/java/org/smartregister/view/dialog/FormRollbackDialogUtilTest.java  1
- opensrp-app/src/main/java/org/smartregister/view/activity/FormConfigurationJsonFormActivity.java  3
- opensrp-app/src/test/java/org/smartregister/view/activity/FormConfigurationJsonFormActivityTest.java  1
- opensrp-app/src/main/java/org/smartregister/view/dialog/FormRollbackDialogUtil.java  5
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/OpenSRP/opensrp-client-core/pullRequest?prid=5565225&bid=18250044)
